import eslintPluginUnicorn from "eslint-plugin-unicorn";
import globals from "globals";

/** @type {import("eslint").Linter.Config} */
const unicornConfig = {
  languageOptions: { globals: globals.builtin },
  plugins: { unicorn: eslintPluginUnicorn },
  rules: {
    "unicorn/better-regex": 0,
    "unicorn/catch-error-name": 2,
    "unicorn/consistent-destructuring": 2,
    "unicorn/consistent-function-scoping": 0,
    "unicorn/custom-error-definition": 0,
    "unicorn/empty-brace-spaces": 0,
    "unicorn/error-message": 2,
    "unicorn/escape-case": 0,
    "unicorn/expiring-todo-comments": 0,
    "unicorn/explicit-length-check": 2,
    "unicorn/filename-case": 0,
    "unicorn/import-style": 0,
    "unicorn/new-for-builtins": 0,
    "unicorn/no-abusive-eslint-disable": 2,
    "unicorn/no-array-callback-reference": 2,
    "unicorn/no-array-for-each": 0,
    "unicorn/no-array-method-this-argument": 2,
    "unicorn/no-array-push-push": 2,
    "unicorn/no-array-reduce": 0,
    "unicorn/no-await-expression-member": 0,
    "unicorn/no-console-spaces": 0,
    "unicorn/no-document-cookie": 2,
    "unicorn/no-empty-file": 2,
    "unicorn/no-for-loop": 2,
    "unicorn/no-hex-escape": 0,
    "unicorn/no-instanceof-array": 2,
    "unicorn/no-invalid-remove-event-listener": 2,
    "unicorn/no-keyword-prefix": 0,
    "unicorn/no-lonely-if": 2,
    "unicorn/no-negated-condition": 2,
    "unicorn/no-nested-ternary": 2,
    "unicorn/no-new-array": 2,
    "unicorn/no-new-buffer": 2,
    "unicorn/no-null": 0,
    "unicorn/no-object-as-default-parameter": 2,
    "unicorn/no-process-exit": 0,
    "unicorn/no-static-only-class": 2,
    "unicorn/no-thenable": 2,
    "unicorn/no-this-assignment": 2,
    "unicorn/no-typeof-undefined": 2,
    "unicorn/no-unnecessary-await": 2,
    "unicorn/no-unreadable-array-destructuring": 2,
    "unicorn/no-unreadable-iife": 2,
    "unicorn/no-unused-properties": 0,
    "unicorn/no-useless-fallback-in-spread": 2,
    "unicorn/no-useless-length-check": 2,
    "unicorn/no-useless-promise-resolve-reject": 2,
    "unicorn/no-useless-spread": 2,
    "unicorn/no-useless-switch-case": 2,
    "unicorn/no-useless-undefined": 2,
    "unicorn/no-zero-fractions": 2,
    "unicorn/number-literal-case": 2,
    "unicorn/numeric-separators-style": 2,
    "unicorn/prefer-add-event-listener": 2,
    "unicorn/prefer-array-find": 2,
    "unicorn/prefer-array-flat": 2,
    "unicorn/prefer-array-flat-map": 2,
    "unicorn/prefer-array-index-of": 2,
    "unicorn/prefer-array-some": 2,
    "unicorn/prefer-at": 2,
    "unicorn/prefer-code-point": 2,
    "unicorn/prefer-date-now": 2,
    "unicorn/prefer-default-parameters": 2,
    "unicorn/prefer-dom-node-append": 2,
    "unicorn/prefer-dom-node-dataset": 2,
    "unicorn/prefer-dom-node-remove": 2,
    "unicorn/prefer-dom-node-text-content": 2,
    "unicorn/prefer-event-target": 2,
    "unicorn/prefer-export-from": 2,
    "unicorn/prefer-includes": 0,
    "unicorn/prefer-json-parse-buffer": 2,
    "unicorn/prefer-keyboard-event-key": 2,
    "unicorn/prefer-logical-operator-over-ternary": 2,
    "unicorn/prefer-math-trunc": 2,
    "unicorn/prefer-modern-dom-apis": 2,
    "unicorn/prefer-modern-math-apis": 2,
    "unicorn/prefer-module": 2,
    "unicorn/prefer-native-coercion-functions": 2,
    "unicorn/prefer-negative-index": 0,
    "unicorn/prefer-node-protocol": 2,
    "unicorn/prefer-number-properties": 2,
    "unicorn/prefer-object-from-entries": 2,
    "unicorn/prefer-optional-catch-binding": 2,
    "unicorn/prefer-prototype-methods": 0,
    "unicorn/prefer-query-selector": 2,
    "unicorn/prefer-reflect-apply": 2,
    "unicorn/prefer-regexp-test": 2,
    "unicorn/prefer-set-has": 0,
    "unicorn/prefer-set-size": 0,
    "unicorn/prefer-spread": 2,
    "unicorn/prefer-string-replace-all": 2,
    "unicorn/prefer-string-slice": 2,
    "unicorn/prefer-string-starts-ends-with": 2,
    "unicorn/prefer-string-trim-start-end": 2,
    "unicorn/prefer-switch": 2,
    "unicorn/prefer-ternary": 2,
    "unicorn/prefer-top-level-await": 2,
    "unicorn/prefer-type-error": 2,
    "unicorn/prevent-abbreviations": [
      2,
      {
        allowList: {
          args: true,
          ctx: true,
          db: true,
          Db: true,
          env: true,
          Env: true,
          params: true,
          props: true,
          ref: true,
          util: true,
          Util: true,
          utils: true,
          Utils: true,
        },
        replacements: { err: { error: true } },
      },
    ],
    "unicorn/relative-url-style": 2,
    "unicorn/require-array-join-separator": 2,
    "unicorn/require-number-to-fixed-digits-argument": 2,
    "unicorn/require-post-message-target-origin": 2,
    "unicorn/string-content": 0,
    "unicorn/switch-case-braces": 2,
    "unicorn/template-indent": 2,
    "unicorn/text-encoding-identifier-case": 2,
    "unicorn/throw-new-error": 2,
  },
};

export default unicornConfig;
